import Foundation

/// Intelligent Content Router that handles URL-based transcription
/// Uses Python script with youtube-transcript-api for YouTube
final class URLTranscriptionService: ObservableObject, @unchecked Sendable {
    static let shared = URLTranscriptionService()
    
    // MARK: - Published State
    @Published var isProcessing = false
    @Published var currentPhase: ProcessingPhase = .idle
    @Published var progress: Double = 0
    @Published var statusMessage: String = ""
    @Published var transcriptionResult: String?
    @Published var error: TranscriptionError?
    
    // MARK: - Types
    
    enum ProcessingPhase: Equatable {
        case idle
        case analyzing
        case fetchingYouTubeTranscript
        case downloadingAudio
        case processingWithWhisper
        case complete
        case failed
    }
    
    enum TranscriptionError: LocalizedError {
        case invalidURL
        case networkError(String)
        case noTranscriptAvailable
        case downloadFailed(String)
        case whisperFailed(String)
        case pythonNotFound
        case dependencyMissing(String)
        case cancelled

        private var isSpanishUI: Bool {
            UserDefaults.standard.string(forKey: "app_ui_language") == "es"
        }

        private func localized(_ spanish: String, _ english: String) -> String {
            isSpanishUI ? spanish : english
        }
        
        var errorDescription: String? {
            switch self {
            case .invalidURL:
                return localized("URL inválida", "Invalid URL")
            case .networkError(let msg):
                return localized("Error de red: \(msg)", "Network error: \(msg)")
            case .noTranscriptAvailable:
                return localized("No hay transcripción disponible", "No transcription available")
            case .downloadFailed(let msg):
                return localized("Error de descarga: \(msg)", "Download error: \(msg)")
            case .whisperFailed(let msg):
                return localized("Error de transcripción: \(msg)", "Transcription error: \(msg)")
            case .pythonNotFound:
                return localized("Python no encontrado", "Python not found")
            case .dependencyMissing(let dep):
                return localized("Dependencia faltante: \(dep)", "Missing dependency: \(dep)")
            case .cancelled:
                return localized("Operación cancelada", "Operation cancelled")
            }
        }
    }
    
    // MARK: - Python Script Response
    
    struct PythonResponse: Codable {
        let success: Bool
        let platform: String?
        let text: String?
        let language: String?
        let isAutoGenerated: Bool?
        let wordCount: Int?
        let needsWhisper: Bool?
        let audioPath: String?
        let error: String?
        let message: String?
        let method: String?
        
        enum CodingKeys: String, CodingKey {
            case success, platform, text, language, error, message, method
            case isAutoGenerated = "is_auto_generated"
            case wordCount = "word_count"
            case needsWhisper = "needs_whisper"
            case audioPath = "audio_path"
        }
    }
    
    // MARK: - Private Properties
    
    private var activeTask: Task<Void, Never>?
    private var activeProcess: Process?  // yt-dlp or python process
    private var isCancelled = false
    private let appSupportDir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        .appendingPathComponent("TranscriptorNative")
    
    private var pythonPath: String {
        let paths = ["/opt/homebrew/bin/python3", "/usr/local/bin/python3", "/usr/bin/python3"]
        return paths.first { FileManager.default.fileExists(atPath: $0) } ?? "python3"
    }

    private var isSpanishUI: Bool {
        UserDefaults.standard.string(forKey: "app_ui_language") == "es"
    }

    private func localized(_ spanish: String, _ english: String) -> String {
        isSpanishUI ? spanish : english
    }
    
    // MARK: - Init
    
    private init() {}
    
    // MARK: - Public API
    
    func transcribe(urlString: String, shouldDownloadAudioFirst: Bool = false) async {
        // Reset cancelled state
        isCancelled = false
        
        await MainActor.run {
            self.isProcessing = true
            self.currentPhase = .analyzing
            self.progress = 0
            self.statusMessage = self.localized("Analizando enlace...", "Analyzing link...")
            self.transcriptionResult = nil
            self.error = nil
        }
        
        AppLogger.shared.log(
            "🔗 [URLService] Starting transcription for: \(urlString) (shouldDownloadAudioFirst: \(shouldDownloadAudioFirst))",
            level: .info,
            category: .transcription
        )
        
        // Optional path: skip subtitle extraction and go directly to audio download.
        if shouldDownloadAudioFirst {
            _ = await downloadAudioFromURL(urlString: urlString)
            return
        }
        
        // Try Python script first (uses youtube-transcript-api)
        await MainActor.run {
            self.currentPhase = .fetchingYouTubeTranscript
            self.statusMessage = self.localized("Obteniendo subtítulos...", "Fetching subtitles...")
            self.progress = 0.3
        }
        
        let result = await runPythonScript(url: urlString)
        
        if result.success, let text = result.text, !text.isEmpty {
            await MainActor.run {
                self.transcriptionResult = text
                self.currentPhase = .complete
                self.progress = 1.0
                self.statusMessage = self.localized("¡Transcripción obtenida!", "Transcription ready!")
                self.isProcessing = false
            }
            AppLogger.shared.log("✅ [URLService] Python script success: \(result.wordCount ?? 0) words", level: .info, category: .transcription)
            return
        }
        
        AppLogger.shared.log("⚠️ [URLService] Python script failed: \(result.message ?? "unknown")", level: .warning, category: .transcription)
        
        // Fallback: Try native Swift approach for YouTube
        await MainActor.run {
            self.statusMessage = self.localized("Intentando método alternativo...", "Trying fallback method...")
            self.progress = 0.5
        }
        
        if let videoId = extractYouTubeVideoId(from: urlString) {
            do {
                let transcript = try await fetchYouTubeTranscriptViaInnertube(videoId: videoId)
                await MainActor.run {
                    self.transcriptionResult = transcript
                    self.currentPhase = .complete
                    self.progress = 1.0
                    self.statusMessage = self.localized("¡Transcripción obtenida!", "Transcription ready!")
                    self.isProcessing = false
                }
                return
            } catch {
                AppLogger.shared.log("⚠️ [URLService] Innertube also failed: \(error)", level: .warning, category: .transcription)
            }
        }
        
        // All methods failed
        await MainActor.run {
            self.error = .noTranscriptAvailable
            self.statusMessage = self.localized(
                "No hay transcripción disponible para este vídeo",
                "No transcription is available for this video"
            )
            self.currentPhase = .failed
            self.isProcessing = false
        }
    }
    
    /// Downloads audio from a remote URL using yt-dlp.
    /// Supports YouTube and other platforms handled by yt-dlp.
    /// Returns the downloaded file URL or nil if failed.
    func downloadAudioFromURL(urlString: String) async -> URL? {
        // Reset cancelled state
        isCancelled = false
        
        await MainActor.run {
            self.isProcessing = true
            self.currentPhase = .downloadingAudio
            self.statusMessage = self.localized("Descargando audio...", "Downloading audio...")
            self.progress = 0.1
            self.transcriptionResult = nil
            self.error = nil
        }
        
        // Find yt-dlp
        let ytdlpPaths = ["/opt/homebrew/bin/yt-dlp", "/usr/local/bin/yt-dlp"]
        guard let ytdlpPath = ytdlpPaths.first(where: { FileManager.default.fileExists(atPath: $0) }) else {
            AppLogger.shared.log("❌ [URLService] yt-dlp not found", level: .error, category: .transcription)
            await MainActor.run {
                self.error = .dependencyMissing(
                    self.localized(
                        "yt-dlp no está instalado. Instálalo con: brew install yt-dlp",
                        "yt-dlp is not installed. Install it with: brew install yt-dlp"
                    )
                )
                self.currentPhase = .failed
                self.isProcessing = false
            }
            return nil
        }
        
        // Create temp directory for download
        let tempDir = FileManager.default.temporaryDirectory
        let downloadToken = UUID().uuidString.lowercased()
        let outputPrefix = "url_audio_\(downloadToken)_"
        let outputTemplate = tempDir.appendingPathComponent("\(outputPrefix)%(id)s.%(ext)s").path
        
        AppLogger.shared.log("📥 [URLService] Downloading audio with yt-dlp from: \(urlString)", level: .info, category: .transcription)
        
        return await withCheckedContinuation { [weak self] continuation in
            guard let self = self else {
                continuation.resume(returning: nil)
                return
            }
            
            let process = Process()
            process.executableURL = URL(fileURLWithPath: ytdlpPath)
            process.arguments = [
                "-x",                    // Extract audio
                "--audio-format", "mp3", // Convert to mp3
                "--audio-quality", "0",  // Best quality
                "-o", outputTemplate,    // Output template
                "--no-playlist",         // Don't download playlist
                "--progress",            // Show progress
                urlString
            ]
            
            var env = ProcessInfo.processInfo.environment
            env["PATH"] = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
            process.environment = env
            
            let outputPipe = Pipe()
            let errorPipe = Pipe()
            process.standardOutput = outputPipe
            process.standardError = errorPipe
            
            // Store reference so we can kill it on cancel
            self.activeProcess = process
            
            // Handle progress updates
            errorPipe.fileHandleForReading.readabilityHandler = { [weak self] handle in
                guard let self = self, !self.isCancelled else { return }
                let data = handle.availableData
                if let output = String(data: data, encoding: .utf8), !output.isEmpty {
                    // Parse progress from yt-dlp output
                    if output.contains("%") {
                        if let match = output.range(of: #"(\d+\.?\d*)%"#, options: .regularExpression) {
                            let percentStr = output[match].dropLast()
                            if let percent = Double(percentStr) {
                                Task { @MainActor in
                                    self.progress = 0.1 + (percent / 100.0) * 0.8
                                }
                            }
                        }
                    }
                }
            }
            
            do {
                try process.run()
                DispatchQueue.global().async { [weak self] in
                    process.waitUntilExit()
                    
                    // Clean up handler
                    errorPipe.fileHandleForReading.readabilityHandler = nil
                    self?.activeProcess = nil
                    
                    // Check if was cancelled
                    guard let self = self, !self.isCancelled else {
                        AppLogger.shared.log("🚫 [URLService] Download was cancelled", level: .info, category: .transcription)
                        continuation.resume(returning: nil)
                        return
                    }
                    
                    let exitCode = process.terminationStatus
                    let outputData = outputPipe.fileHandleForReading.readDataToEndOfFile()
                    let outputString = String(data: outputData, encoding: .utf8) ?? ""
                    
                    AppLogger.shared.log("📥 [URLService] yt-dlp exit code: \(exitCode)", level: .info, category: .transcription)
                    
                    // Exit code 15 = SIGTERM (cancelled), don't show error
                    if exitCode != 0 && exitCode != 15 {
                        AppLogger.shared.log("❌ [URLService] yt-dlp failed: \(outputString)", level: .error, category: .transcription)
                        Task { @MainActor in
                            self.error = .downloadFailed(
                                self.localized("Error al descargar el audio", "Failed to download audio")
                            )
                            self.currentPhase = .failed
                            self.isProcessing = false
                        }
                        continuation.resume(returning: nil)
                        return
                    }
                    
                    // If cancelled via SIGTERM, just return nil silently
                    if exitCode == 15 {
                        continuation.resume(returning: nil)
                        return
                    }
                    
                    // Find the downloaded file
                    do {
                        let contents = try FileManager.default.contentsOfDirectory(at: tempDir, includingPropertiesForKeys: nil)
                        let audioFile = contents.first { url in
                            let name = url.lastPathComponent.lowercased()
                            return name.hasPrefix(outputPrefix) && (name.hasSuffix(".mp3") || name.hasSuffix(".m4a") || name.hasSuffix(".webm") || name.hasSuffix(".opus"))
                        }
                        
                        if let audioFile = audioFile {
                            AppLogger.shared.log("✅ [URLService] Audio downloaded: \(audioFile.path)", level: .info, category: .transcription)
                            Task { @MainActor in
                                self.progress = 1.0
                                self.statusMessage = self.localized("¡Audio descargado!", "Audio downloaded!")
                                self.currentPhase = .complete
                                self.isProcessing = false
                            }
                            continuation.resume(returning: audioFile)
                        } else {
                            AppLogger.shared.log("❌ [URLService] Downloaded file not found", level: .error, category: .transcription)
                            Task { @MainActor in
                                self.error = .downloadFailed(
                                    self.localized("No se encontró el archivo descargado", "Downloaded file not found")
                                )
                                self.currentPhase = .failed
                                self.isProcessing = false
                            }
                            continuation.resume(returning: nil)
                        }
                    } catch {
                        AppLogger.shared.log("❌ [URLService] Error finding downloaded file: \(error)", level: .error, category: .transcription)
                        Task { @MainActor in
                            self.error = .downloadFailed(
                                self.localized("Error al buscar el archivo", "Error while locating the file")
                            )
                            self.currentPhase = .failed
                            self.isProcessing = false
                        }
                        continuation.resume(returning: nil)
                    }
                }
            } catch {
                AppLogger.shared.log("❌ [URLService] Failed to start yt-dlp: \(error)", level: .error, category: .transcription)
                Task { @MainActor in
                    self.error = .downloadFailed(
                        self.localized("No se pudo iniciar la descarga", "Could not start the download")
                    )
                    self.currentPhase = .failed
                    self.isProcessing = false
                }
                continuation.resume(returning: nil)
            }
        }
    }
    
    func cancel() {
        AppLogger.shared.log("🚫 [URLService] Cancelling active operations", level: .info, category: .transcription)
        
        // Mark as cancelled
        isCancelled = true
        
        // Kill any running process (yt-dlp, python, etc.)
        if let process = activeProcess, process.isRunning {
            AppLogger.shared.log("🚫 [URLService] Terminating process PID: \(process.processIdentifier)", level: .info, category: .transcription)
            process.terminate()
            // Force kill if still running after a moment
            DispatchQueue.global().asyncAfter(deadline: .now() + 0.5) { [weak self] in
                if let process = self?.activeProcess, process.isRunning {
                    AppLogger.shared.log("🚫 [URLService] Force killing process", level: .warning, category: .transcription)
                    kill(process.processIdentifier, SIGKILL)
                }
            }
        }
        activeProcess = nil
        
        // Cancel Swift task
        activeTask?.cancel()
        activeTask = nil
        
        Task { @MainActor in
            self.error = .cancelled
            self.currentPhase = .failed
            self.isProcessing = false
            self.progress = 0
            self.statusMessage = self.localized("Cancelado", "Cancelled")
        }
    }
    
    // MARK: - Python Script
    
    /// El script Python embebido directamente para evitar acceso a archivos externos
    private let embeddedPythonScript = #"""
#!/usr/bin/env python3
import sys
import json
import re
import html
from urllib.parse import urlparse, parse_qs

def clean_text(text):
    text = html.unescape(text)
    text = text.replace('\n', ' ').replace('\r', '')
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def format_paragraphs(segments):
    if not segments:
        return ""
    paragraphs = []
    current_paragraph = []
    sentence_count = 0
    for segment in segments:
        text = clean_text(segment.get('text', ''))
        if not text:
            continue
        current_paragraph.append(text)
        sentence_endings = len(re.findall(r'[.!?]', text))
        sentence_count += sentence_endings
        if sentence_count >= 5:
            paragraphs.append(' '.join(current_paragraph))
            current_paragraph = []
            sentence_count = 0
    if current_paragraph:
        paragraphs.append(' '.join(current_paragraph))
    return '\n\n'.join(paragraphs)

def extract_youtube_id(url):
    patterns = [
        r'(?:https?://)?(?:www\.)?youtube\.com/watch\?v=([a-zA-Z0-9_-]{11})',
        r'(?:https?://)?(?:www\.)?youtube\.com/embed/([a-zA-Z0-9_-]{11})',
        r'(?:https?://)?(?:www\.)?youtube\.com/shorts/([a-zA-Z0-9_-]{11})',
        r'(?:https?://)?youtu\.be/([a-zA-Z0-9_-]{11})',
        r'(?:https?://)?m\.youtube\.com/watch\?v=([a-zA-Z0-9_-]{11})',
    ]
    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            return match.group(1)
    parsed = urlparse(url)
    query_params = parse_qs(parsed.query)
    if 'v' in query_params:
        video_id = query_params['v'][0]
        if len(video_id) == 11:
            return video_id
    return None

def get_transcript(video_id):
    try:
        from youtube_transcript_api import YouTubeTranscriptApi
        api = YouTubeTranscriptApi()
        language_priority = ['es', 'es-ES', 'es-419', 'en', 'en-US', 'en-GB']
        transcript_data = None
        selected_lang = None
        for lang in language_priority:
            try:
                transcript_data = api.fetch(video_id, languages=[lang])
                selected_lang = lang
                break
            except:
                continue
        if transcript_data is None:
            try:
                transcript_list = api.list(video_id)
                for transcript in transcript_list:
                    transcript_data = transcript.fetch()
                    selected_lang = transcript.language_code
                    break
            except Exception as e:
                return {'success': False, 'error': 'no_transcript', 'message': str(e)}
        if transcript_data is None:
            return {'success': False, 'error': 'no_transcript', 'message': 'No transcript available'}
        segments = []
        for item in transcript_data:
            if hasattr(item, 'text'):
                segments.append({'text': item.text})
            elif isinstance(item, dict):
                segments.append(item)
        formatted_text = format_paragraphs(segments)
        if not formatted_text:
            return {'success': False, 'error': 'empty', 'message': 'Empty transcript'}
        return {
            'success': True,
            'text': formatted_text,
            'language': selected_lang,
            'word_count': len(formatted_text.split()),
            'method': 'youtube_transcript_api'
        }
    except Exception as e:
        return {'success': False, 'error': 'failed', 'message': str(e)}

def main():
    if len(sys.argv) < 2:
        print(json.dumps({'success': False, 'error': 'missing_url'}))
        sys.exit(1)
    url = sys.argv[1]
    video_id = extract_youtube_id(url)
    if not video_id:
        print(json.dumps({'success': False, 'error': 'invalid_url', 'message': 'Could not extract video ID'}))
        sys.exit(1)
    result = get_transcript(video_id)
    result['video_id'] = video_id
    result['platform'] = 'youtube'
    print(json.dumps(result, ensure_ascii=False))
    sys.exit(0 if result.get('success') else 1)

if __name__ == '__main__':
    main()
"""#
    
    private func getScriptPath() -> String {
        // Escribir el script en un directorio temporal (no requiere permisos)
        let tempDir = FileManager.default.temporaryDirectory
        let scriptPath = tempDir.appendingPathComponent("url_transcriber.py").path
        
        // Solo escribir si no existe o es diferente
        if !FileManager.default.fileExists(atPath: scriptPath) {
            do {
                try embeddedPythonScript.write(toFile: scriptPath, atomically: true, encoding: .utf8)
                AppLogger.shared.log("🐍 [URLService] Script written to temp: \(scriptPath)", level: .info, category: .transcription)
            } catch {
                AppLogger.shared.log("🐍 [URLService] Failed to write script: \(error)", level: .error, category: .transcription)
            }
        }
        
        return scriptPath
    }
    
    private func runPythonScript(url: String) async -> PythonResponse {
        let scriptPath = getScriptPath()
        
        let emptyResponse = PythonResponse(
            success: false, platform: nil, text: nil, language: nil,
            isAutoGenerated: nil, wordCount: nil, needsWhisper: nil,
            audioPath: nil,
            error: "unknown",
            message: localized("Error desconocido", "Unknown error"),
            method: nil
        )
        
        // Check if already cancelled
        guard !isCancelled else {
            return emptyResponse
        }
        
        AppLogger.shared.log("🐍 [URLService] Running Python script: \(scriptPath)", level: .info, category: .transcription)
        AppLogger.shared.log("🐍 [URLService] Python path: \(pythonPath)", level: .info, category: .transcription)
        AppLogger.shared.log("🐍 [URLService] URL argument: \(url)", level: .info, category: .transcription)
        
        return await withCheckedContinuation { [weak self] continuation in
            guard let self = self else {
                continuation.resume(returning: emptyResponse)
                return
            }
            
            let process = Process()
            process.executableURL = URL(fileURLWithPath: self.pythonPath)
            process.arguments = [scriptPath, url, "transcript"]
            
            var env = ProcessInfo.processInfo.environment
            env["PATH"] = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
            process.environment = env
            
            let outputPipe = Pipe()
            let errorPipe = Pipe()
            process.standardOutput = outputPipe
            process.standardError = errorPipe
            
            // Store reference so we can kill it on cancel
            self.activeProcess = process
            
            do {
                try process.run()
                DispatchQueue.global().async { [weak self] in
                    process.waitUntilExit()
                    self?.activeProcess = nil
                    
                    // Check if was cancelled
                    guard let self = self, !self.isCancelled else {
                        continuation.resume(returning: emptyResponse)
                        return
                    }
                    
                    let exitCode = process.terminationStatus
                    
                    // Exit code 15 = SIGTERM (cancelled)
                    if exitCode == 15 {
                        continuation.resume(returning: emptyResponse)
                        return
                    }
                    
                    let outputData = outputPipe.fileHandleForReading.readDataToEndOfFile()
                    let errorData = errorPipe.fileHandleForReading.readDataToEndOfFile()
                    
                    let outputString = String(data: outputData, encoding: .utf8) ?? ""
                    let errorString = String(data: errorData, encoding: .utf8) ?? ""
                    
                    AppLogger.shared.log("🐍 [URLService] Exit code: \(exitCode)", level: .info, category: .transcription)
                    AppLogger.shared.log("🐍 [URLService] Output length: \(outputString.count) chars", level: .info, category: .transcription)
                    AppLogger.shared.log("🐍 [URLService] Output preview: \(String(outputString.prefix(500)))", level: .info, category: .transcription)
                    
                    if !errorString.isEmpty {
                        AppLogger.shared.log("🐍 [URLService] Stderr: \(errorString)", level: .warning, category: .transcription)
                    }
                    
                    guard !outputString.isEmpty else {
                        AppLogger.shared.log("🐍 [URLService] Empty output from Python script", level: .error, category: .transcription)
                        continuation.resume(returning: emptyResponse)
                        return
                    }
                    
                    guard let jsonData = outputString.data(using: .utf8) else {
                        AppLogger.shared.log("🐍 [URLService] Failed to convert output to data", level: .error, category: .transcription)
                        continuation.resume(returning: emptyResponse)
                        return
                    }
                    
                    do {
                        let response = try JSONDecoder().decode(PythonResponse.self, from: jsonData)
                        AppLogger.shared.log("🐍 [URLService] Decoded response - success: \(response.success), wordCount: \(response.wordCount ?? 0), text length: \(response.text?.count ?? 0)", level: .info, category: .transcription)
                        continuation.resume(returning: response)
                    } catch {
                        AppLogger.shared.log("🐍 [URLService] JSON decode error: \(error)", level: .error, category: .transcription)
                        continuation.resume(returning: emptyResponse)
                    }
                }
            } catch {
                AppLogger.shared.log("🐍 [URLService] Failed to start process: \(error)", level: .error, category: .transcription)
                continuation.resume(returning: emptyResponse)
            }
        }
    }
    
    // MARK: - YouTube Helpers
    
    private func extractYouTubeVideoId(from urlString: String) -> String? {
        guard let url = URL(string: urlString), let host = url.host?.lowercased() else { return nil }
        
        let youtubeHosts = ["youtube.com", "www.youtube.com", "m.youtube.com", "youtu.be"]
        guard youtubeHosts.contains(host) else { return nil }
        
        // youtu.be short links
        if host.contains("youtu.be") {
            return url.pathComponents.dropFirst().first
        }
        
        // Standard ?v= parameter
        if let components = URLComponents(url: url, resolvingAgainstBaseURL: false),
           let videoId = components.queryItems?.first(where: { $0.name == "v" })?.value {
            return videoId
        }
        
        // /embed/, /v/, /shorts/ paths
        for pattern in ["/embed/", "/v/", "/shorts/"] {
            if let range = urlString.range(of: pattern) {
                let afterPattern = urlString[range.upperBound...]
                let videoId = String(afterPattern.prefix(while: { $0 != "?" && $0 != "&" && $0 != "/" }))
                if !videoId.isEmpty { return videoId }
            }
        }
        
        return nil
    }
    
    private func fetchYouTubeTranscriptViaInnertube(videoId: String) async throws -> String {
        AppLogger.shared.log("🔄 [URLService] Trying innertube API for: \(videoId)", level: .info, category: .transcription)
        
        let infoURL = URL(string: "https://www.youtube.com/youtubei/v1/player?key=AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8")!
        
        var request = URLRequest(url: infoURL)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36", forHTTPHeaderField: "User-Agent")
        
        let body: [String: Any] = [
            "context": ["client": ["clientName": "WEB", "clientVersion": "2.20240101.00.00"]],
            "videoId": videoId
        ]
        request.httpBody = try? JSONSerialization.data(withJSONObject: body)
        
        let (data, _) = try await URLSession.shared.data(for: request)
        
        guard let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let captions = json["captions"] as? [String: Any],
              let renderer = captions["playerCaptionsTracklistRenderer"] as? [String: Any],
              let tracks = renderer["captionTracks"] as? [[String: Any]] else {
            throw TranscriptionError.noTranscriptAvailable
        }
        
        AppLogger.shared.log("✅ [URLService] Found \(tracks.count) caption tracks", level: .info, category: .transcription)
        
        // Find best transcript URL
        guard let transcriptURL = findBestTranscriptURL(from: tracks) else {
            throw TranscriptionError.noTranscriptAvailable
        }
        
        // Fetch transcript
        let transcript = try await fetchAndParseTranscript(from: transcriptURL)
        
        if transcript.isEmpty {
            throw TranscriptionError.noTranscriptAvailable
        }
        
        return transcript
    }
    
    private func findBestTranscriptURL(from tracks: [[String: Any]]) -> String? {
        let langPriority = ["es", "es-ES", "es-419", "en", "en-US"]
        
        // Try manual transcripts first
        for lang in langPriority {
            for track in tracks {
                if let langCode = track["languageCode"] as? String,
                   langCode.hasPrefix(String(lang.prefix(2))),
                   let kind = track["kind"] as? String, kind != "asr",
                   let baseUrl = track["baseUrl"] as? String {
                    return baseUrl.replacingOccurrences(of: "\\u0026", with: "&")
                }
            }
        }
        
        // Then auto-generated
        for lang in langPriority {
            for track in tracks {
                if let langCode = track["languageCode"] as? String,
                   langCode.hasPrefix(String(lang.prefix(2))),
                   let baseUrl = track["baseUrl"] as? String {
                    return baseUrl.replacingOccurrences(of: "\\u0026", with: "&")
                }
            }
        }
        
        // Fallback to first available
        return tracks.first?["baseUrl"] as? String
    }
    
    private func fetchAndParseTranscript(from urlString: String) async throws -> String {
        var transcriptURL = urlString
        if !urlString.contains("fmt=json3") {
            transcriptURL += (urlString.contains("?") ? "&" : "?") + "fmt=json3"
        }
        
        guard let url = URL(string: transcriptURL) else {
            throw TranscriptionError.networkError(localized("URL inválida", "Invalid URL"))
        }
        
        var request = URLRequest(url: url)
        request.setValue("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36", forHTTPHeaderField: "User-Agent")
        
        let (data, _) = try await URLSession.shared.data(for: request)
        
        guard let content = String(data: data, encoding: .utf8) else {
            throw TranscriptionError.networkError(localized("No se pudo decodificar respuesta", "Could not decode response"))
        }
        
        return parseTranscript(content)
    }
    
    private func parseTranscript(_ content: String) -> String {
        var segments: [String] = []
        
        // Try JSON format first
        if content.trimmingCharacters(in: .whitespaces).hasPrefix("{"),
           let data = content.data(using: .utf8),
           let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
           let events = json["events"] as? [[String: Any]] {
            
            for event in events {
                if let segs = event["segs"] as? [[String: Any]] {
                    for seg in segs {
                        if let text = seg["utf8"] as? String {
                            let cleaned = decodeHTMLEntities(text)
                            if !cleaned.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                                segments.append(cleaned)
                            }
                        }
                    }
                }
            }
        }
        
        // Fallback to XML format
        if segments.isEmpty {
            let pattern = "<text[^>]*>([^<]*)</text>"
            if let regex = try? NSRegularExpression(pattern: pattern, options: []) {
                let matches = regex.matches(in: content, options: [], range: NSRange(content.startIndex..., in: content))
                for match in matches {
                    if let range = Range(match.range(at: 1), in: content) {
                        let text = decodeHTMLEntities(String(content[range]))
                        if !text.trimmingCharacters(in: .whitespaces).isEmpty {
                            segments.append(text)
                        }
                    }
                }
            }
        }
        
        // Format into paragraphs
        return formatParagraphs(segments)
    }
    
    private func decodeHTMLEntities(_ text: String) -> String {
        var result = text
        let entities = [("&amp;", "&"), ("&lt;", "<"), ("&gt;", ">"), 
                       ("&quot;", "\""), ("&#39;", "'"), ("&apos;", "'"), 
                       ("\\n", " "), ("\n", " ")]
        for (entity, char) in entities {
            result = result.replacingOccurrences(of: entity, with: char)
        }
        return result.trimmingCharacters(in: .whitespaces)
    }
    
    private func formatParagraphs(_ segments: [String]) -> String {
        var paragraphs: [String] = []
        var current: [String] = []
        var sentenceCount = 0
        
        for segment in segments {
            current.append(segment)
            sentenceCount += segment.filter { ".!?".contains($0) }.count
            
            if sentenceCount >= 5 {
                paragraphs.append(current.joined(separator: " ").replacingOccurrences(of: "  ", with: " "))
                current = []
                sentenceCount = 0
            }
        }
        
        if !current.isEmpty {
            paragraphs.append(current.joined(separator: " "))
        }
        
        return paragraphs.joined(separator: "\n\n")
    }
}
